### PR TITLE
Possible Refactor

### PR DESCRIPTION
**Pull request by sbussetti**
I'm not certain you'll actually want to incorporate this pull request verbatim, but I wanted to submit it in order to call out a few issues and potential means for resolving them.

The first is the pickling/migration issue.  Making the same class global over and over again is not a fix, as it overwrites all preceding class definitions created using the factory function.  In my branch here, I'm doing some simple metaclassing that creates a differently named class global based on the superclasses provided and the name of the visibility setting.  This prevents differently configured Managers/Queries from overwriting eachother when they're added to globals.

Second thing is an enhancement.  Maybe less useful for you, but handy for me -- I've also added in 2 new signals for post_soft_delete and post_soft_create so I can listen to when these occur instead of trying to deduce this with conditionals in my normal post_save handler.

### CODE REVIEW

**Comment by Gagaro** [comment]
As I said in the other PR, I started to do it in https://github.com/Gagaro/django-safedelete/tree/refactor_mixin. I think we should get rid of the factories altogether as it has raised a lot of issues (see #20). Keeping them will only lead to over-complicated solution (against the KISS philosophy). The refactoring seems to work fine but I couldn't test it on a real project yet and I'm not quite happy with having `_safedelete_*` attributes on the model to configure it but I'm not sure if there's a better solution.

Could you try with this branch (maybe on 4dde1023d4d58ec7b8b241d8631ca0450c2cdd30 commit as I added #14 too after) and tell me if it works for you ?

The signals are a nice addition but should be in another PR as it is a separate issue. If my branch works for you, don't hesitate to make a PR there.

Thanks

**Comment by sbussetti** [comment]
Ah! Just saw this.  Yeah, without some manner of factory pattern, you're not gonna get away from needing to add class attributes to the subclass.  Maybe it could be a part of `Meta`?  

Anyway, I've only been testing on Django 1.8, so I'm not surprised things are failing for <1.7 on my branch.  I'll check out your refactor branch and go from there!

**Comment by Gagaro** [comment]
I looked at how to add paramaters to Meta but it seems to be a real hassle
(the Meta options being instanciated in the metaclass). If you find a way
to do it without pain, I'd be really interested.

2016-01-13 18:21 GMT+01:00 Steve Bussetti <notifications@github.com>:

> Ah! Just saw this. Yeah, without some manner of factory pattern, you're
> not gonna get away from needing to add class attributes to the subclass.
> Maybe it could be a part of Meta?
>
> Anyway, I've only been testing on Django 1.8, so I'm not surprised things
> are failing for <1.7 on my branch. I'll check out your refactor branch and
> go from there!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makinacorpus/django-safedelete/pull/40#issuecomment-171370331>
> .
>



-- 
Gagaro

**Comment by sbussetti** [comment]
Yeah I suppose adding to Meta is a long-running open issue.  (https://code.djangoproject.com/ticket/5793)  so nevermind that.

I see the commit you're pointing at, and it lgtm, but could you also push the associated 0.4.x branch up to origin so I can work off that appropriately?  Thanks!

**Comment by Gagaro** [comment]
https://github.com/makinacorpus/django-safedelete/tree/0.4.x

Also I looked at your signal naming and I find `softcreate` a bit odd. What do you think about `restore` or something similar instead ?

**Comment by sbussetti** [comment]
Softcreate seemed to be the natural opposite of softdelete to me, since the kind of actions you’d take on that signal would be the same as, or similar to those you’d take on the built in `post_save` when created=True.  That’s my reasoning there, although I’ve got no problem changing the naming to restore when I re-create the commit for 0.4.x.

On January 14, 2016 at 9:23:43 AM, Gagaro (notifications@github.com) wrote:

https://github.com/makinacorpus/django-safedelete/tree/0.4.x

Also I looked at your signal naming and I find softcreate a bit odd. What do you think about restore or something similar instead ?

**Comment by Gagaro** [comment]
It's just that I think softcreate isn't really self-explanatory at a first
glance. Maybe softundelete?

2016-01-14 15:31 GMT+01:00 Steve Bussetti <notifications@github.com>:

> Softcreate seemed to be the natural opposite of softdelete to me, since
> the kind of actions you’d take on that signal would be the same as, or
> similar to those you’d take on the built in `post_save` when created=True.
> That’s my reasoning there, although I’ve got no problem changing the naming
> to restore when I re-create the commit for 0.4.x.
>
> On January 14, 2016 at 9:23:43 AM, Gagaro (notifications@github.com)
> wrote:
>
> https://github.com/makinacorpus/django-safedelete/tree/0.4.x
>
> Also I looked at your signal naming and I find softcreate a bit odd. What
> do you think about restore or something similar instead ?
>
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makinacorpus/django-safedelete/pull/40#issuecomment-171658108>
> .
>



-- 
Gagaro

**Comment by sbussetti** [comment]
Hey good call, just plain old `post_undelete` seems fine to me!

**Comment by Gagaro** [comment]
Also the datetime changed is in the 0.4.x branch, maybe you wanted it without?

`post_undeleted` works for me :+1:.

**Comment by sbussetti** [comment]
I'm cool with whatever the prevailing feature is going to be.  Having a datetime for last deleted is not relevant to my use cases, but it doesn't really hurt either I guess.

**Comment by sbussetti** [comment]
closing this in favor of 0.4.x branch

**Pull request closed without merging**
