### PR TITLE
Rename SafeDeleteMixin to SafeDeleteModel

### LINKED ISSUE #55: SafeDeleteMixin is not a mixin
The name `SafeDeleteMixin` seems to say that the class is a Mixin when it's not because it inherits from `django.db.models`. Wouldn't `SafeDeleteModel`be a better name in this case? It clears up some confusion regarding inheritance.

### PR DESCRIPTION
**Pull request by wli**
Fixes #55

### CODE REVIEW

**Comment by wli** [comment]
I went ahead and made this breaking change. I tried keeping the Mixin version around also, but ran into some troubles with the tests. Maybe we can bring it back in a separate PR if anyone actually needs it.

**Comment by Gagaro** [comment]
The mixin class should still be usable but throw a deprecation warning. Please see http://stackoverflow.com/questions/9008444/how-to-warn-about-class-name-deprecation for example.

**Comment by wli** [comment]
@Gagaro It throws a DeprecationWarning now

**Comment by Gagaro** [comment]
Thanks, can you also make the change in the doc ? Also this is now conflicting with your other PR.

**Comment by wli** [comment]
@Gagaro updated all instances of SafeDeleteMixin to SafeDeleteModel in docs, and fixed the merge conflict.

**Comment by Gagaro** [comment]
The tests are broken. Also can you change `base model` to `abstract model`, please see my comment above.

It should be good to merge after that :).

**Comment by Gagaro** [comment]
No problem, there should be `SafeDeleteModel` in the docs too, I didn't think about that when reviewing :+1: .

**Comment by wli** [comment]
Which part of the docs?

**Comment by wli** [comment]
I added references in `models.rst`: https://github.com/makinacorpus/django-safedelete/pull/71/files#diff-850598850f808b61b99f86c40616870fL7

**Comment by Gagaro** [comment]
Thanks :+1:

**Pull request merged**
