### PR TITLE
Configurable VISIBLE_BY_PK field in the settings

### PR DESCRIPTION
**Pull request by yahia13**
Hey!

I wanted to use a different field for making my masked instance visible so I added the ability to set this in the settings.

If you like it and plan to merge I can write tests.

Thanks

### CODE REVIEW

**Comment by Gagaro** [comment]
Sure, just a question: what is the use of `_validate_visible_by_field`? It should be handled by django in the queryset if the field does not exist.

Please also add documentation for this new setting (https://github.com/makinacorpus/django-safedelete/blob/master/docs/models.rst).

Thanks :+1: .

**Comment by yahia13** [comment]
I thought it is userful if you wrote the wrong field in settings. But on second thought it is unnecessary since i only call it when you call the .get/.filter which is already too late.

Will remove it

**Comment by Gagaro** [comment]
Please don't delete `DELETED_VISIBLE_BY_PK`, it will break current project using it. You should assign them the same value to ensure backward compatibility.

Also, in the documentation, you can add ``:py:data:`DELETED_INVISIBLE` `` to have a link to the paragraph. (ie: ``The field is configurable with :py:data:`DELETED_INVISIBLE```)

**Comment by yahia13** [comment]
Hope this is better now. Please let me know if you something else needs to be changed.

**Comment by Gagaro** [comment]
Actually I'm wondering if it would not be better to add a parameter to the factory to set the field to lookup by model rather than having a global setting. It could even simplify this feature.

What do you think about it?

**Comment by yahia13** [comment]
Hmm.. it does make more sense to have it by model to be more flexible but in this case how should it be implemented? The factory should have both `visibility` parameter and `visibility_field` which defaults to pk? should it also save the `visibility_field` then in the manager class so that you can retrieve it per model if you forgot what you put?

**Comment by Gagaro** [comment]
Yes there should be an additional `visibility_field` parameter.

I don't think we should save it in the manager class, it's not something we actually save in the DB. We can just look in the code if we want to see the field.

**Comment by yahia13** [comment]
Done

**Comment by Gagaro** [comment]
Nice :+1: .

Is the `CategoryPK` still needed in the tests?

**Comment by yahia13** [comment]
yes, it is making sure using DELETED_VISIBLE_BY_PK still works. You don't think so?

**Comment by Gagaro** [comment]
I'm not sure that's needed as it should be deprecated and removed in the future. But why not for now.

**Comment by Gagaro** [comment]
Thanks :+1: !

**Comment by yahia13** [comment]
You are welcome! Okay then.

Are you planning to do a release on pypi? I am planning to use this in a project now so would be awesome if i can just install django-safedelete :D

**Comment by Gagaro** [comment]
Sure, it's released :).

**Pull request merged**
