### PR TITLE
Add configurable option to have a boolean field in SafeDeleteModels.

### PR DESCRIPTION
**Pull request by gonzaloamadio**
Some (probably legacy db) has boolean fields as well. This PR add the option to have this field set when deleting. 

The main reason to have this field is database indexes. It’s a lot easier to index (and multi-index) on a boolean than a datetime.

Now I am not using that field to do filtering, but can modify it to do so.

### CODE REVIEW

**Comment by Gagaro** [comment]
Hi, thanks for the PR but I already said I was against such a thing in #165, which DB are you using that it is easier to index as a boolean? You can easily add conditional index in postgres for example to index only non-null values.

**Comment by gonzaloamadio** [comment]
> Hi, thanks for the PR but I already said I was against such a thing in #165, which DB are you using that it is easier to index as a boolean? You can easily add conditional index in postgres for example to index only non-null values.

Hi, thank you for the response. I am using postgres.

Should I add 2 indexes for each field?. Something like. Because I am planning to search on deleted and non-deleted elements.

```
create index if not exists idx_table_name_deleted on table (name) where deleted_at is null;
create index if not exists idx_table_name_not_deleted on table (name) where deleted_at is not null;
```

**Comment by Gagaro** [comment]
What is your issue with indexes? A simple index should do the job just fine with null values.

**Comment by Gagaro** [comment]
What I meant to say is that postgres does index null values. An index on the deleted column should be used for both cases.

**Pull request closed without merging**
