### PR TITLE
fix of deprecation warning for django 4

### PR DESCRIPTION
**Pull request by znotdead**

### CODE REVIEW

**Comment by Gagaro** [comment]
This would break translations for 1.11 which we still support.

I think the only way to fix that is to change the import depending on the Django version.

**Comment by znotdead** [comment]
Should we drop support django < 2 as many libraries already did this and release major version?

**Comment by Gagaro** [comment]
Yes I think we can drop support for Django < 2.2 now and release a 0.6.0.

**Comment by znotdead** [comment]
Thanks. Will fix travis CI than.

**Comment by violuke** [comment]
Could you also swap to [Semantic Versioning](https://semver.org/) when this goes in? This release should really be a 1.0.0 release not a 0.6.0. This is really helpful for people using [Poetry](https://github.com/python-poetry/poetry) and hopefully Pip will make the transition too. Thanks for the great package :+1:

**Comment by Gagaro** [comment]
Fix in last release with others deprecation warnings.

**Pull request closed without merging**
