### PR TITLE
Soft cascade

### PR DESCRIPTION
**Pull request by gibaneido**
I had to use a SOFT_DELETE_CASCADE. See what they think of the implementation.

### CODE REVIEW

**Comment by Gagaro** [comment]
Thanks for the contribution.

This breaks when a `SOFT_DELETE_CASCADE` is made with a normal Django model linked (see https://github.com/makinacorpus/django-safedelete/commit/dabf84821f6b1fd8e53cb1f1a203700c6ee1ebb2).

This would be easy to solve with 0.4 (just an `ininstance` test), but it's gonna be tricky on the 0.3 (and probably not very accurate). Maybe checking for the attribute `deleted` is the best for this version..

Also, could you add a line in the `CHANGELOG`.

Thanks.

**Comment by alanjds** [comment]
So, when doing the cascade on a non-softdelete related it should not be deleted? Had I understood the test right?

**Comment by Gagaro** [comment]
The issue is that the default `delete` method for Django models does not have a `force_policy` kwarg, so it will raise an exception.

I guess models in this case should be ignored (just like it is for a non-cascading soft delete).

**Comment by gibaneido** [comment]
@Gagaro ,
thank you for your attention!
see what you think of this approach that checks the module of related class.
the attribute ´´deleted´´ can be used in many other implementations from outside, so checking for this attribute would not guarantee the class belongs to this lib.

´´CHANGELOG´´ updated
Thanks

**Comment by Gagaro** [comment]
Perfect, thanks 👍 .

I won't be able to do the release before Monday though.

**Pull request merged**
