### PR TITLE
Dynamic model superclass

### PR DESCRIPTION
**Pull request by gibaneido**
Hi,
I had trouble using a third package which implements a django custom model. This pull request allow us to pass as parameter a CustomModel.

Thanks

### CODE REVIEW

**Comment by Gagaro** [comment]
Once again something that shouldn't be an issue with 0.4. It seems strange that `WrongEdition` wouldn't have the method though. I'll try this out tomorrow, thanks.

**Comment by Gagaro** [comment]
That's an issue with the order of the inheritance, your model should be `class WrongEdition(SoftDeleteMixin, CustomModel):`.

Please take a look at Python MRO for more information (for example: https://makina-corpus.com/blog/metier/2014/python-tutorial-understanding-python-mro-class-search-path).

**Comment by alanjds** [comment]
We was trying to do multiple inheritance with [django-polymorphic](https://django-polymorphic.readthedocs.io/en/stable/managers.html), but had issues with the multiple inheritance: only one behaviour was honored, no matter what the order of parents are on the class declaration. Seems to be related to both being parents of ``django.db.models.Model``.

I guessed by the name particle "mixin" that it has inherited from the bare ``object``...

Let me ask something: I saw commits on ``master``, ``3.x`` and ``4.x`` branches. Is 4.x considered released/stable? If so, we can switch to 4.x and save everybody some burden, but can only do that if it is already released & stable.

**Comment by Gagaro** [comment]
And you passed the `PolymorphicManager` as `manager_superclass`?

I never had the opportunity to try it in an actual production, that's why I was asking for feedback in #43. The code is almost the same though, I got rid of the factories and `deleted` is now a datetime (I didn't put that in 0.3 to avoid breaking existing project using safedelete). I didn't have any issue in the personal project I used it in so far.

**Comment by alanjds** [comment]
Yes, we passed the ``manager_superclass`` and ``queryset_superclass``, but was ignored. I suspect it to be about ``PolymorphicModel._default_queryset``, but not sure.

Someone will eat my guts if I use beta/RC stuff for now on our ongoing project, but if it is just this the change... I need to get some talk here.

**Comment by Gagaro** [comment]
Let me know what you end up doing, If needed, I can merge this PR.

**Comment by alanjds** [comment]
Thanks @Gagaro. Right now @gibaneido is trying the 4.x branch and will issue 1 or 2 PRs I guess. Maybe we can end up creating a specific test against Polymorphic, I dont know... Anyway, @gibaneido is on it.

**Comment by gibaneido** [comment]
Hi @Gagaro, i spent too long time trying implement safedelete with django-polymorfic. At this time, we'll go to continue on the 0.3 version. Can you merge this PR please? Do you need anything else to be done from us?

**Comment by Gagaro** [comment]
I just need you to rebase on master and move the changelog to the last version before merging. Then it should be all good.

**Comment by gibaneido** [comment]
If you need, shout us!!

**Comment by Gagaro** [comment]
I'm not sure what you mean, but yes, I need you to do the rebase before merging.

**Comment by gibaneido** [comment]
@Gagaro , sorry for the delay. Is that what you needed?

**Comment by gibaneido** [comment]
hi,
is that ok to be merged?

**Comment by Gagaro** [comment]
Hi, I commented one line of your test case, can you answer to that first? Thanks.

**Comment by gibaneido** [comment]
I can't find your comment.
Can you please link or redo???

**Comment by Gagaro** [comment]
I pinged you in the comment, did you see it ?

**Comment by gibaneido** [comment]
I can not see

**Comment by Gagaro** [comment]
Ok I'll paste it here:

```python
+    def test_custom_model_fail(self):
+        self.assertTrue(hasattr(Edition, "customMethod"))
```

Isn't this supposed to be WrongEdition?

**Comment by gibaneido** [comment]
Fixed ;-)

**Comment by Gagaro** [comment]
Perfect, Thanks :+1:

**Pull request merged**
