### PR TITLE
Alert user when uniqueness violated by deleted object

### PR DESCRIPTION
**Pull request by ShmuelTreiger**
Re-reading your comments in #185, I have understood that raising an error can be done in the normal model, but reviving existing deleted objects on `create()` would be a separate model (as opposed to a flag). Please let me know if I have misunderstood.

As far as the code, I present two options:
1) Check from within `_perform_unique_checks()` if uniqueness is violated by a deleted object
2) Wrap Django's `create()` class with some custom code to perform the same uniqueness check

The advantage of option 1 is that it's a universal check for all use cases, not just `create()`.

The advantage of option 2 is that if the one changed line in safedelete's `_perform_unique_checks()` can ever be simplified, safedelete won't have to maintain the rest of the Django method.

Both options make one additional query to the database.

I am partial to option 2 for maintainability. Let me know your thoughts.

(Will add tests once path has been finalized.)

### CODE REVIEW

**Comment by Gagaro** [comment]
I think it should be done in `_perform_unique_checks`, because that's the place where we have the exact unique constraints which fails.

Your code in `create` wouldn't work either. The queryset would only catch objects with the exact same values than the ones passed to `create`, where you should filter on the unique fields which are causing the issue (which is done in the `_perform_unique_checks`).

Maybe the best thing to do here would be to add an error in `_perform_unique_checks` when the constraint is broken by a deleted object pointing to the documentation about the partial unique constraints.

**Comment by ShmuelTreiger** [comment]
So, it turns out `_perform_unique_checks` isn't called for .create() or .save() (only for validation). Django just goes straight through and lets the database reject the UniqueConstraint violation.

Thoughts on another/best way to proceed?

On the potential plus side, playing around with it inspired an option for replacing it, see #195 .

**Comment by Gagaro** [comment]
Django only does validation when forms are submitted, I actually think it's all right if we do validate ourselves only in those cases too.

As I said, I don't like the current behavior of reviving objects when updating. The behaviors should be predictable and adding on top of that would only add more confusion IMO.

**Comment by ShmuelTreiger** [comment]
>Django only does validation when forms are submitted, I actually think it's all right if we do validate ourselves only in those cases too.

That's nice, and we can add it, but I really think that if I'm using `.save()` or `.create()` and I get an integrityerror, it would be helpful to know if the existing object is soft deleted. For me at least. When I first ran into this problem, it definitely took me a while to realize that the object was deleted.

>As I said, I don't like the current behavior of reviving objects when updating.

Sounds like it's time for safedelete 2.0? (Or at least 1.2?)

**Comment by Gagaro** [comment]
> > Django only does validation when forms are submitted, I actually think it's all right if we do validate ourselves only in those cases too.
> 
> That's nice, and we can add it, but I really think that if I'm using `.save()` or `.create()` and I get an integrityerror, it would be helpful to know if the existing object is soft deleted. For me at least. When I first ran into this problem, it definitely took me a while to realize that the object was deleted.
 
The issue is that integrity errors are not limited to uniqueness errors. Documenting this is probably the best we can do without adding overhead queries which won't be useful in a lot of cases.

> > As I said, I don't like the current behavior of reviving objects when updating.
> 
> Sounds like it's time for safedelete 2.0? (Or at least 1.2?)

Yes not reviving objects by default would be a good candidate for a new major release with #197 .

**Comment by Gagaro** [comment]
It will be an extra query per unique constraint, for an issue which could be from another thing entirely.

**Pull request closed without merging**
