### PR TITLE
Add new safedelete admin filter

### LINKED ISSUE #171: SafeDeleteAdminFilter
I just wrote an admin filter which filters for non-deleted, all, and deleted. Not sure if something like this has been suggested before, so I thought I'd offer it and see if any interest:

```
  class SoftDeleteAdminFilter(admin.SimpleListFilter):
      title = "deleted"
      parameter_name = "deleted"
  
      # Overriding from sourcecode (not strictly necessary):
      # https://github.com/django/django/blob/main/django/contrib/admin/filters.py#L62
      def choices(self, changelist):
          yield {
              'selected': self.value() is None,
              'query_string': changelist.get_query_string(remove=[self.parameter_name]),
              'display': _('All (Excluding Deleted)'),  # This line changed
          }
          for lookup, title in self.lookup_choices:
              yield {
                  'selected': self.value() == str(lookup),
                  'query_string': changelist.get_query_string({self.parameter_name: lookup}),
                  'display': title,
              }
  
      def lookups(self, request, model_admin):
          lookups = (
              ('deleted', 'All (Including Deleted)'),
              ('deleted_only', 'Deleted Only'),
          )
          return lookups
  
      def queryset(self, request, queryset):
          deleted = True
          if self.value() == "deleted":
              return queryset
          elif self.value() == "deleted_only":
              deleted = False
          return queryset.filter(deleted__isnull=deleted)
```

### PR DESCRIPTION
**Pull request by ShmuelTreiger**
Closes #171 

Created this filter as indicated in my issue. I'm having trouble, however, figuring out how to programmatically change the filter value for testing. See the TODOs. Hoping someone can help me out.

Based on what I found [here](https://stackoverflow.com/questions/16751325/test-a-custom-filter-in-admin-py), I tried something like this:

```
filter = SoftDeleteAdminFilter(request=None, params={FIELD_NAME: FIELD_NAME}, model=Category, model_admin=self.modeladmin)
self.assertTrue(filter.queryset(None, Category.objects.filter(pk=self.categories[1].pk))[0])
```

But no luck.

### CODE REVIEW

**Comment by Gagaro** [comment]
Hi, thanks for the PR :+1: .

The easiest way would be to create another `ModelAdmin` in the test file inheriting from `SafeDeleteAdmin` and including the filter, the same way `CategoryAdmin` is done.

**Comment by ShmuelTreiger** [comment]
I'm not sure where that gets me. So I do

```
class CategoryAdmin2(SafeDeleteAdmin):
    list_filter = (SoftDeleteAdminFilter,)
```

I still can't figure out how to change the filter value?

```
    def test_soft_delete_admin_filter(self):
        self.modeladmin = CategoryAdmin2
        self.modeladmin.list_filter[0].value = FIELD_NAME
```
Doesn't work?

**Comment by Gagaro** [comment]
So actually, it only shows as 3 tests in Pycharm. But it should show all errors:

```
$ python runtests.py safedelete.tests.test_admin.AdminTestCase.test_soft_delete_admin_filter
Creating test database for alias 'default'...
System check identified no issues (0 silenced).

======================================================================
ERROR: test_soft_delete_admin_filter (safedelete.tests.test_admin.AdminTestCase) (name='FIELD_NAME')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gagaro/django/modules/django-safedelete/safedelete/tests/test_admin.py", line 108, in test_soft_delete_admin_filter
    raise ValueError()
ValueError

======================================================================
ERROR: test_soft_delete_admin_filter (safedelete.tests.test_admin.AdminTestCase) (name='FIELD_NAME_only')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gagaro/django/modules/django-safedelete/safedelete/tests/test_admin.py", line 118, in test_soft_delete_admin_filter
    raise ValueError()
ValueError

----------------------------------------------------------------------
Ran 1 test in 0.285s

FAILED (errors=2)
Destroying test database for alias 'default'...

```

**Comment by ShmuelTreiger** [comment]
Yes, it shows in the errors (see the pdf I attached). If that's sufficient for you, then great, I'll rename then and be done with it.

**Comment by Gagaro** [comment]
Merged manually to fix the conflicts. Thanks for the PR :+1: .

**Pull request closed without merging**
